### PR TITLE
Fix the saltversion test

### PR DESCRIPTION
**Pull request by elemoine**

### CODE REVIEW

**Comment by cloudlab-autobuild** [comment]
Can one of the admins verify this patch?

**Comment by elemoine** [comment]
This aims to fix the saltversion test done in `env.sls`. This is WIP and untested right now.

**Comment by atengler** [comment]
I tested this change and you are right, I accidentally reversed the condition before commiting the final state, after this patch it should work as intended, thanks

**Comment by elemoine** [comment]
Thanks!

**Pull request merged**
